# Generated by Django 4.0.2 on 2022-03-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopper',
            name='phone',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
