# Generated by Django 4.0.2 on 2022-03-26 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_shopper_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=128, verbose_name='Pays')),
                ('city', models.CharField(blank=True, max_length=128, verbose_name='Ville')),
                ('common', models.CharField(blank=True, max_length=128, verbose_name='Commune')),
                ('quarter', models.CharField(blank=True, max_length=128, verbose_name='Quartier')),
                ('street_door', models.CharField(blank=True, max_length=128, verbose_name='Rue et porte')),
                ('zipcode', models.CharField(blank=True, max_length=128, verbose_name='Code postal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
