# Generated by Django 4.0.2 on 2022-04-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_shopper_email_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='loc',
            field=models.CharField(blank=True, max_length=128, verbose_name='GPS'),
        ),
    ]
