# Generated by Django 4.0.2 on 2022-04-08 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_paymentmethodtypes_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethodtypes',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentmethodtypes',
            name='method',
            field=models.CharField(max_length=100, verbose_name='Methode de paiement'),
        ),
    ]
