# Generated by Django 4.0.2 on 2022-04-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_paymentmethodtypes_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethodtypes',
            name='user',
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='method',
            field=models.CharField(max_length=100, verbose_name='Methode de paiement'),
        ),
    ]
