# Generated by Django 4.0.2 on 2022-04-06 15:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_ordered_order_finished_remove_order_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
