# Generated by Django 4.0.2 on 2022-04-07 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
