# Generated by Django 4.0.2 on 2022-04-09 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_sold_count_alter_categorie_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='Nombre de vues'),
        ),
    ]
